export const firmSchema = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  image: [
    "https://hrizantema.rs/images/aside/hrizantema-cvecara-gmb.jpg",
    "https://hrizantema.rs/images/venci/bela-ruza-beli-gerber-bela-kala-robelini-prirodni-venac.jpg",
    "https://hrizantema.rs/images/venci/ruza-crvena-oblik-srce-venac.jpg",
  ],
  currenciesAccepted: ["USD", "EUR", "RSD"],
  openingHours: "Mo-Su 07:00-16:00",
  address: {
    "@type": "PostalAddress",
    postalCode: "11000",
    addressLocality: "Groblje Orlovaca",
    streetAddress: "Groblje Orlovača lok 30",
    addressCountry: "Srbija",
  },
  aggregateRating: {
    "@type": "AggregateRating",
    reviewCount: "300",
    bestRating: "5",
    worstRating: "5",
    ratingValue: "5.0",
  },
  contactPoint: {
    "@type": "ContactPoint",
    availableLanguage: ["en", "rs"],
    contactType: "Prodavac",
    email: "sztrhrizantema@gmail.com",
    telephone: "+381692050441",
    url: "https://hrizantema.rs",
  },
  logo: "https://hrizantema.rs/imgs/logo.png",
  geo: {
    "@type": "GeoCoordinates",
    latitude: "44.709651100497574",
    longitude: "20.412431569495617",
  },
  name: "Hrizantema",
  url: "https://hrizantema.rs",
  telephone: "+381692050441",
  priceRange: "$$",
  legalName: "Hrizantema 1994",
};
